close all; clear all; clc;

addpath(genpath('../'));
compile = 1;


% compilex mex
if compile
  mex COMPFLAGS="/openmp" OPTIMFLAGS="/O2" ... 
  writeDescriptor_mex.cpp ...
  numerics1.cpp frot.cpp splines.cpp fproj.cpp ...
  library.cpp flimage.cpp filter.cpp ...
  compute_asift_matches.cpp ...
  demo_lib_sift.cpp compute_asift_keypoints.cpp ...
  libMatch/match.cpp libNumerics/numerics.cpp ...
  orsa.cpp ...
  io_png/io_png.c ...
  io_png/libs/png/png.c io_png/libs/png/pngerror.c io_png/libs/png/pnggccrd.c io_png/libs/png/pngget.c ...
  io_png/libs/png/pngmem.c io_png/libs/png/pngpread.c io_png/libs/png/pngread.c io_png/libs/png/pngrio.c io_png/libs/png/pngrtran.c ...
  io_png/libs/png/pngrutil.c io_png/libs/png/pngset.c io_png/libs/png/pngtest.c io_png/libs/png/pngtrans.c io_png/libs/png/pngvcrd.c ...
  io_png/libs/png/pngwio.c io_png/libs/png/pngwrite.c io_png/libs/png/pngwtran.c io_png/libs/png/pngvcrd.c io_png/libs/png/pngwutil.c ...
  io_png/libs/zlib/adler32.c io_png/libs/zlib/compress.c io_png/libs/zlib/crc32.c io_png/libs/zlib/deflate.c io_png/libs/zlib/gzio.c ...
  io_png/libs/zlib/infback.c io_png/libs/zlib/inffast.c io_png/libs/zlib/inflate.c io_png/libs/zlib/inftrees.c ... io_png/libs/zlib/minigzip.c ...
  io_png/libs/zlib/trees.c io_png/libs/zlib/uncompr.c io_png/libs/zlib/zutil.c
end



% marker
m = ['wi'; 'du'; 'ci'; 'be'; 'fi'; 'ma'];

for mi = 1:6
  fprintf([m(mi, :), '\n']);
  imwrite(rgb2gray(imread(['../' m(mi, :) '.png'])), 'tmp.png');
  writeDescriptor_mex('tmp.png', ['../' m(mi, :) '.key']);
end